### ISSUE TITLE
Pointing output at single file produces malformed TAR archive

### ISSUE THREAD

**Issue by tazjin** [polydawn/repeatr#87]
With an output spec such as:

```yaml
outputs:
  "executable":
    type: "tar"
    mount: "/go/src/github.com/tazjin/quinistry/quinistry"
    silo: "file://quinistry.tar.gz"
```

and that `mount` being the executable itself, we get a malformed TAR as the header is written like for a directory:

```
# tar xvf quinistry.tar.gz 
./
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

```
# tar tvf quinistry.tar.gz 
drwxr-xr-x 1000/1000   6128052 2010-01-01 00:00 ./
```
